export const tokens = {
  light: {
    '--bg':          '#FAFAF8',
    '--bg-card':     '#FFFFFF',
    '--bg-subtle':   '#F5F5F2',
    '--bg-hover':    '#F0EFEA',
    '--border':      '#EBEBEA',
    '--border-mid':  '#D6D6D3',
    '--text':        '#0A0A0A',
    '--text-mid':    '#5A5A56',
    '--text-dim':    '#9B9B97',
    '--green':       '#1A7A4A',
    '--green-tint':  '#E8F5EE',
    '--green-text':  '#1A7A4A',
    '--red':         '#C0392B',
    '--red-tint':    '#FDECEA',
    '--amber':       '#92600A',
    '--amber-tint':  '#FDF3E3',
    '--blue':        '#2563EB',
    '--blue-tint':   'rgba(37,99,235,0.08)',
    '--purple':      '#7C3AED',
    '--purple-tint': 'rgba(124,58,237,0.08)',
    '--ink':         '#0A0A0A',
    '--cream':       '#FAFAF8',
  },
  dark: {
    '--bg':          '#0A0A0A',
    '--bg-card':     '#111110',
    '--bg-subtle':   '#1A1A18',
    '--bg-hover':    '#222220',
    '--border':      '#2A2A28',
    '--border-mid':  '#3A3A38',
    '--text':        '#FAFAF8',
    '--text-mid':    '#9B9B97',
    '--text-dim':    '#5A5A56',
    '--green':       '#2EAD6A',
    '--green-tint':  '#0D2B1A',
    '--green-text':  '#2EAD6A',
    '--red':         '#E05C4B',
    '--red-tint':    '#2B1210',
    '--amber':       '#D4A84B',
    '--amber-tint':  '#2B2010',
    '--blue':        '#60A5FA',
    '--blue-tint':   'rgba(96,165,250,0.1)',
    '--purple':      '#A78BFA',
    '--purple-tint': 'rgba(167,139,250,0.12)',
    '--ink':         '#FAFAF8',
    '--cream':       '#0A0A0A',
  },
};
export const applyTokens = (theme) =>
  Object.entries(tokens[theme]).forEach(([k, v]) =>
    document.documentElement.style.setProperty(k, v));

